### ISSUE TITLE
Page d'accueil après connexion

### ISSUE THREAD

**Issue by Tijani-M** [Tijani-M/AllForKids#1]
Après connecxion il y a redirection vers  AllForKids/src/ScolariteBundle/Resources/views/Default/index.html.twig

**Comment by Hafedh-K** [comment]
Résolu par redirection au niveau du DefaultControler du ScolariteBundle, vers une nouvelle page Home crée dans le ScolariteBundle.
La redirection par défaut vers l'index du Bundle Scolarité est parceque c'était le premier bundle créé.
